// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWCoh3wDcdprfimvfzNwLEMfjSglCDv_w',
    appId: '1:837819833458:web:0dbc8f10cb21bf5b68b6eb',
    messagingSenderId: '837819833458',
    projectId: 'facebook-b55ac',
    authDomain: 'facebook-b55ac.firebaseapp.com',
    storageBucket: 'facebook-b55ac.appspot.com',
    measurementId: 'G-DF7K4VWJXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKrF_WK2nR177yhgDnTSyS_nVPoVGsOXc',
    appId: '1:837819833458:android:7ca0f57d76ca985268b6eb',
    messagingSenderId: '837819833458',
    projectId: 'facebook-b55ac',
    storageBucket: 'facebook-b55ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY3z_IrM-xczJ0rmkc_rH9OchH6lBAhZk',
    appId: '1:837819833458:ios:bfc6998a585bd08a68b6eb',
    messagingSenderId: '837819833458',
    projectId: 'facebook-b55ac',
    storageBucket: 'facebook-b55ac.appspot.com',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY3z_IrM-xczJ0rmkc_rH9OchH6lBAhZk',
    appId: '1:837819833458:ios:bfc6998a585bd08a68b6eb',
    messagingSenderId: '837819833458',
    projectId: 'facebook-b55ac',
    storageBucket: 'facebook-b55ac.appspot.com',
    iosBundleId: 'com.example.facebook',
  );
}
